### ISSUE TITLE
Foliant replace skips lines containing images

### ISSUE THREAD

**Issue by pavelkim** [foliant-docs/foliantcontrib.replace#1]
There is a condition that makes the plugin skip all lines containing `![` substring for both words and regex: [L47](https://github.com/foliant-docs/foliantcontrib.replace/blob/30f22c063076c2a3e5f417b55096c3ab509dff01/foliant/preprocessors/replace.py#L47) [L61](https://github.com/foliant-docs/foliantcontrib.replace/blob/30f22c063076c2a3e5f417b55096c3ab509dff01/foliant/preprocessors/replace.py#L61)
Though, putting an image in the middle of a sentence looks like a common move to make. 

We probably could look for image tags in each line, split it on parts, skip replacement for certain parts (for images and urls?) and then glue it back together. 

For images and urls it might be a good idea to come up with a separate class of replacements along with words and regex — URLs and images.

**Comment by apkraft** [comment]
Fixed in new version.
